function [figure1]=createfigure(lat1, lon1, sizedata1,badcountydata,j)

% Create figure
figure1 = figure;

% Create geobubble
geobubble(figure1,lat1,lon1,sizedata1,...
    'Title',sprintf('%s%s','Total Drug Reports Graph of ',num2str(j)),...
    'Basemap','grayland',...
    'SizeLimits',[0 33513],...
    'BubbleWidthRange',[1 20],...
    'SizeLegendTitle','Maximum Reports in 2010-2017');
geolimits('auto');

% Create textbox
annotation(figure1,'textbox',...
    [.7 .73 .265 .38],...
    'String',{'Top Reports County'},...
    'FitBoxToText','on');

annotation(figure1,'textbox',...
    [.7 .1 .265 .6],...
    'String',{strjoin(strcat(num2str(badcountydata.TotalDrugReportsCounty),...
    {' '},lower(badcountydata.StateCountyName)),'\n')},...
    'FitBoxToText','off');



